project:
  type: website
  output-dir: docs
  render:
    - "*.ipynb"
    - "*.qmd"

format:
  html:
    theme: pandoc
    max-width: 60em
    html-math-method: mathml
#    number-sections: true
    code-line-numbers: true
    highlight-style: haddock
    #toc: true
    toc-title: " "
    embed-resources: true
    mainfont: Source Serif Pro, charter, palatino, serif
    linestretch: 1.6
    fontsize: 16px
#  pdf:
#    documentclass: article
#    margin-left: 30mm
#    margin-right: 30mm