# 研究领域介绍

这篇文章主要是写给想找我做 "本科毕设" 的本科生.

我的研究领域是应用微观理论, 主要使用博弈论和机制设计相关的工具.
想在我指导下写本科毕业论文的同学, 可以从以下范围内选择题目. 

下面提到的相关论文都可以在网上下载.

## 授权 (Delegation)

授权模型最早源于Holmstrom在组织经济学中的工作, 随后在垄断管制, 关税制定, 行为经济学等领域有所应用. 这一类文献已十分丰富. 我在一篇和澳洲莫纳什大学赵小健教授合作的论文 (已发表于 BEJTE) 中构建了一个投资人-理财顾问的互动模型, 考察投资人的金融素养会如何影响他的授权行为. 主要创新点是在投资人进行授权前, 加入了理财顾问的信息披露行为. 我们发现理财顾问倾向于向金融素养较高的投资人进行更多的披露.   

此外, 我在和武汉大学胡枭骁助理教授合作的一篇论文中, 比较了 (i) 基于限制行为人行动集合的授权和 (ii) 保留否决权 (veto right) 的授权行为. 我们发现, 当委托人和代理人利益冲突较大时, 后者是最优的, 否则前者最优.

2021年我指导的刘宇同学选择了授权相关的题目 (他在准备毕业论文的同时考研到了复旦大学经济思想史专业). 根据我之前的经验, 如果你有一定的博弈论基础, 这个题目的难度是合适的.


## 动态机制设计 (Dynamic mechanism design)

传统的机制设计问题 (如 Myerson 的拍卖模型)主要关注静态和一维的情形, 近年来经济学家愈发关注动态和高维的机制设计问题, 这类情境下的卖家最优机制和 Myerson 的结果完全不同: 最优机制可能是随机的, 满足 BIC (贝叶斯激励形容) 而非 DSIC (优势策略激励相容), 等等. 我有一篇文章考虑机票定价的模型, 放松了 Courty and Li (2000) 中关于卖家承诺能力的假设. 我发现, 当卖家不能在初期承诺在未来维持高价时, Courty and Li (2000) 中考虑的机制并不可行; 相应的, 卖家可以给初期的消费者提供最低价格保障 (low price guarantee), 从而缓解因无法进行承诺所带来的时间不一致问题.

机制设计问题起源于博弈论的研究, 但发展至今其用到的主要工具和方法已和博弈论十分不同. 现在的机制设计论文主要使用线性规划 (linear programming) 和概率论的技巧. 我个人认为, 机制设计是博弈论当下最火热 (从发文数量来看确实如此, 尽管其中 90% 以上的论文都是计算机系的人发的), 最有前景的领域~~之一~~. 如果你有较好的概率论和最优化基础, 我十分建议你选择这个领域作为毕业论文题目. 这个领域很新, 即使是最简单的 1-seller, 1-buyer, 2-goods 情形, 也还有很多我们暂时不清楚的地方. 其中的一些小问题很适合拿来练手, 作为本科生毕业论文的题目.

## 信息设计 (Information design) ∩ 产业组织

信息设计的研究起源于 Kamenica 和 Gentzkow 于 2011年发表的 Bayesian persuasion 一文. 这类文章的特点是假设有信息优势的一方 (信息发送者) 具有很强的承诺能力, 并且能够选择任何 Blackwell 实验作为信号. 在这些假设的基础上, 作者对均衡中行为人的收益集合给出了很简洁的几何刻画. 此后研究者们从各种角度对 KG 的模型进行了拓展. 我有一篇文章在 KG 的基础上加入了一个效用函数为最大化社会福利的规划者, 他可以在实验结果出来前发布一个公共信号. 文章的主要结论是信息发送者设计的实验精度和规划者的信号精度严格负相关, 针对信息结构的比较揭示了规划者面临的 sender-receiver 之间福利的权衡取舍. 由于这个领域的新文章很多, 研究的问题又相对集中, 我的文章难免和其他人发生了撞车.   

现在我对把信息设计的元素加入产业组织的研究中比较感兴趣. 它可以和国内当下较火热的网购平台监管联系起来, 如淘宝和拼多多. 平台类似信息设计中的信号发送者, 它可以帮消费者了解产品的信息. 同时, 平台又对上游的厂商收取费用. 如果可以刻画出一个均衡, 即使是很简单的情形, 也是很好的本科论文题目. 

如果你对这个题目感兴趣, 或许不需要太多博弈论基础, 因为信息设计的主要工具和传统的博弈很不一样. 相应地, 你可能需要额外了解一些统计学中的工具, 如  blackwell dominance, information ranking (给函数排序) 等.          

---

以上是关于我研究的介绍. 我不建议之前没有博弈论基础的同学选择我当指导老师. 此外, 如果你对微观经济学领域的其他问题感兴趣 (如产业组织, 行为经济学理论, 决策论等), 也欢迎和我交流. 即使你对我的研究领域感兴趣, 我也鼓励学生自己选择论文题目. 根据我的经验, 对于自己拟定的题目学生往往动力更足.

最后, 我没有太多关于经验研究 (empirical research) 的经验. 如果你的论文主要内容是经验的部分, 我大概率不是最合适的人选.
湖大经贸院有很多做经验研究的老师 (如易淳, 何淑华, 冀云阳等, 详情见教师个人主页), 他们会更适合你.   

如果你是湖大的学生, 关于毕业论文选题有任何问题都欢迎给我发邮件: hlei@hnu.edu.cn. 

雷浩然

2021/11/17